### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by penzn** [WebAssembly/reference-sysroot#6]
Sharing linear memory between WASM and JavaScript without shared memory management is slightly hazardous -- one side can easily clobber what the other wrote. It would be beneficial to provide C memory management functionality in wasm libc, that can be used for both JS and WebAssembly, similar to what Rust [does][r].

[r]: https://www.hellorust.com/demos/canvas/index.html

**Comment by penzn** [comment]
Ping @sunfishcode

**Comment by sunfishcode** [comment]
Host bindings has evolved into [WebIDL bindings](https://github.com/WebAssembly/webidl-bindings) which is evolving further and aiming to be not specific to the Web. It's an ongoing story, but that's where I expect this issue will be solved, rather than in reference-sysroot.
